#!url=https://raw.githubusercontent.com/sw19999/Shadowrocket/main/jd.module
#!name=京东去广告
#!desc=移除京东开屏广告，精简我的页面产品推广。
#!author=RuCu6 sw1999
#!date=2023-12-24 18:45:15

[Rule]
DOMAIN,dns.jd.com,REJECT
IP-CIDR,101.124.19.122/32,REJECT,no-resolve
IP-CIDR6,2402:db40:5100:1011::5/128,REJECT,no-resolve
URL-REGEX,^http:\/\/\w{32}\.jddebug\.com\/diagnose\?,REJECT

[URL Rewrite]
^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(searchBoxWord|stationPullService|uniformRecommend[06]) - reject-dict

[Script]
移除京东广告 = type=http-response, pattern=^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(deliverLayer|getTabHomeInfo|myOrderInfo|orderTrackBusiness|personinfoBusiness|start|welcomeHome), script-path=https://raw.githubusercontent.com/sw19999/Shadowrocket/main/Loon/jingdong.js, requires-body=true

[MITM]
hostname = %APPEND% api.m.jd.com