
#!name=酷我音乐去广告+VIP
#!desc=移除开屏广告、调用Yuheng0101脚本解锁VIP
#!author=sw1999
#!date=2024-06-06

[Script]
酷我音乐SVIP = type=http-response, pattern=^https?:\/\/(?:musicpay|nmobi|vip1|audiobookpay|tingshu)\.kuwo\.cn\/(?:music\.pay\?newver=\d+|mobi.s\?f=kwxs|vip\/(?:enc\/user\/vip\?op=ui&uid=|v2\/theme\?op=gd)|a\.p|v2\/api\/pay\/user\/info), script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/kuwo.js, requires-body=true, timeout=60
波点音乐VIP = type=http-response,pattern=^https:\/\/bd-api\.kuwo\.cn\/api\/(ucenter\/users|play\/listening\/user|service\/(home\/index|banner\/myPage|advert\/watch)),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/bodian.js
搜索框处理 =type=http-response,requires-body=1,max-size=0,pattern=https?:\/\/searchrecterm\.kuwo\.cn\/recterm\.s, script-path=https://raw.githubusercontent.com/ddgksf2013/dev/main/kuwomusic.js
去除首页轮播广告和tips =type=http-response,requires-body=1,max-size=0,pattern=https?:\/\/mgxhtj\.kuwo\.cn\/mgxh\.s, script-path=https://raw.githubusercontent.com/ddgksf2013/dev/main/kuwomusic.js
去除会员页广告=type=http-response,requires-body=1,max-size=0,pattern=https?:\/\/appi\.kuwo\.cn\/kuwopay\/vip-tab\/page\/cells, script-path=https://raw.githubusercontent.com/ddgksf2013/dev/main/kuwomusic.js
去除会员页顶部广告tab=type=http-response,requires-body=1,max-size=0,pattern=https?:\/\/appi\.kuwo\.cn\/kuwopay\/vip-tab\/setting, script-path=https://raw.githubusercontent.com/ddgksf2013/dev/main/kuwomusic.js

[MITM]
hostname = %APPEND% *.kuwo.cn, *.lrts.me
