
#!name=酷我音乐VIP
#!desc=调用Yuheng0101脚本，解锁VIP，最高支持音质：超品音质
#!author=sw1999
#!date=2024-06-06

[Script]
酷我音乐SVIP = type=http-response, pattern=^https?:\/\/(?:musicpay|nmobi|vip1|audiobookpay|tingshu)\.kuwo\.cn\/(?:music\.pay\?newver=\d+|mobi.s\?f=kwxs|vip\/(?:enc\/user\/vip\?op=ui&uid=|v2\/theme\?op=gd)|a\.p|v2\/api\/pay\/user\/info), script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/kuwo.js, requires-body=true, timeout=60
波点音乐VIP = type=http-response,pattern=^https:\/\/bd-api\.kuwo\.cn\/api\/(ucenter\/users|play\/listening\/user|service\/(home\/index|banner\/myPage|advert\/watch)),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/bodian.js

[MITM]
hostname = %APPEND% *.kuwo.cn, bd-api.kuwo.cn, *.lrts.me
